#!/bin/sh
# ¿lo de arriba esta bien? ¿no deberia ser /bin/make -f $@ o algo asi?

CC = gcc
MAKE = make
EXE = aspectrum
VERSION = 0.1.6

# define as void if you don't want to use agup a cosmetic mod of allegro gui
AGUPDIR=agup-0.9.1
AGUPLIB=$(AGUPDIR)/agup.a

# remember to uncomment the adecuated target for each arquitecture.

# target: Linux/GCC
# include Makefile.lnx

# Target: MS-DOS/DJGPP
# include Makefile.dos

# Target: Windows/mingw32
# include Makefile.min

# linux
DESTDATPATH = /usr/share/$(EXE)
LFLAGS = `allegro-config --libs`
CFLAGS = -Wall -O3 -mcpu=i686 `allegro-config --cflags` \
        -DVERSION=\"$(VERSION)\" -DDESTDAT=\"$(DESTDATPATH)\" \
        -DSOUND_BY_STREAM -DI_HAVE_AGUP -I$(AGUPDIR)
RM = rm
EXT=

# windos (mingw32)
#LFLAGS = -lalleg 
#CFLAGS = -DVERSION=\"$(VERSION)\" -DNO_GETOPTLONG -Wall -O2 -mwindows \
#       -DSOUND_BY_STREAM
#RM= del
#EXT=.exe

# esto no se pa que valdra. ( es pa debug )
DBGLIB = -lmss -g
DBGDEF = -DMSS -D_DEBUG_

# esto todabia no lo uso
DESTDOCPATH = /usr/share/doc/$(EXE)
DESTEXEPATH = /usr/bin

# fuentes y objetos para linux. 
files = sound.c v_alleg.c snaps.c graphics.c menu.c debugger.c \
main.c z80.c disasm.c 
objects=sound.o v_alleg.o snaps.o graphics.o menu.o debugger.o \
main.o z80.o disasm.o 

# objetos para windows las fuentes no hacen falta por que se usa makedeps.bat
#objects=sound.o v_alleg.o snaps.o graphics.o menu.o debugger.o \
#main.o z80.o disasm.o contrib/getopt.o

all: aspectrum

aspectrum: dep $(AGUPLIB) $(objects) 
	$(CC) $(EXTRA) -o $(EXE) $(objects) $(AGUPLIB) $(LFLAGS) 

$(objects): %.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@

$(AGUPLIB):
	$(MAKE) -C $(AGUPDIR)

#linux dep
dep:
	echo >deps
	for i in $(files) ; do $(CC) -MM $$i >>deps ; done

#dos dep
#dep:
#	makedeps.bat

clean:
	-$(RM) *.o 
	-$(RM) $(EXE)$(EXT) 
	-$(RM) deps
	-$(MAKE) -C $(AGUPDIR) clean

todo: clean all

-include deps

# some unused stuff
debug:
	$(CC) $(EXTRA) -o $(EXE) $(FILES) $(ALL_FLAGS) $(DBGLIB) $(DBGDEF)

#.phony clean
