#!/bin/sh

CC = gcc
EXE = aspectrum
VERSION = -0.1
ALL_FLAGS := -lalleg
EXTRA :=
FILES = z80.c disasm.c snaps.c graphics.c debugger.c main.c v_alleg.c menu.c

all:
	@echo MAKING ALL:
	@echo Compiling and linking the executable ...
	@echo
	$(CC) $(EXTRA) -o $(EXE) $(FILES) $(ALL_FLAGS)
	@echo
	@exit


clean:
	@echo CLEAN:
	@echo Deleting the $(EXE) binary ...
	@if [ -f $(EXE) ]; then \
	rm $(EXE); \
	fi
	@echo 
	@exit
